import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("online 2v2 uses Firebase signaling and STUN-only WebRTC", async () => {
  const source = await readFile(new URL("../app/online-room.ts", import.meta.url), "utf8");
  const firebaseClient = await readFile(new URL("../app/firebase-client.ts", import.meta.url), "utf8");
  assert.match(source, /stun:stun\.l\.google\.com:19302/);
  assert.doesNotMatch(source, /turns?:/i);
  assert.match(source, /createDataChannel\("factor-force"/);
  assert.match(source, /rooms\/\$\{code\}\/signals/);
  assert.match(source, /OnlineMatchSize = 2 \| 4/);
  assert.match(source, /matchSize: requestedMatchSize/);
  assert.match(source, /initialRoom = \(await get\(roomReference\)\)\.val\(\)/);
  assert.match(source, /slotOwners\/slot\$\{candidate\}/);
  assert.match(source, /current === null \? uid : undefined/);
  assert.match(firebaseClient, /setPersistence\(auth, browserSessionPersistence\)/);
  assert.match(source, /orderByChild\("status"\)/);
  assert.match(source, /equalTo\("waiting"\)/);
  assert.match(source, /limitToLast\(40\)/);
  assert.match(source, /refreshRooms/);
  assert.match(source, /roomsUnsubscribe\.current = onValue\(roomsQuery/);
  assert.match(source, /roomPlayers\.length >= roomMatchSize \|\| !host/);
  assert.match(source, /if \(isHostRef\.current\) \{\s*void remove\(ref\(database, `rooms\/\$\{code\}`\)\)/);
  assert.match(source, /ROOM_HEARTBEAT_INTERVAL_MS = 15_000/);
  assert.match(source, /ROOM_STALE_AFTER_MS = 60_000/);
  assert.match(source, /hostLastSeen: serverTimestamp\(\)/);
  assert.match(source, /staleRoomCodes\.forEach/);
  assert.match(source, /crypto\.subtle\.digest\("SHA-256"/);
  assert.match(source, /passwordHash !== initialRoom\.passwordHash/);
});

test("ranked accounts persist points, nicknames, and expose a top-50 leaderboard", async () => {
  const accountSource = await readFile(new URL("../app/ranked-account.ts", import.meta.url), "utf8");
  const battleSource = await readFile(new URL("../app/free-battle.tsx", import.meta.url), "utf8");
  const rules = await readFile(new URL("../firebase/database.rules.json", import.meta.url), "utf8");
  assert.match(accountSource, /createUserWithEmailAndPassword/);
  assert.match(accountSource, /signInWithEmailAndPassword/);
  assert.match(accountSource, /processedMatches/);
  assert.match(accountSource, /Math\.round\(32 \* \(actual - expected\)\)/);
  assert.match(accountSource, /limitToLast\(50\)/);
  assert.match(accountSource, /updateDisplayName/);
  assert.match(accountSource, /updateProfile\(currentUser, \{ displayName: name \}\)/);
  assert.match(battleSource, /온라인 랭킹 TOP 50/);
  assert.match(battleSource, /온라인 배틀넷/);
  assert.match(battleSource, /마이페이지/);
  assert.match(battleSource, /계정생성하기/);
  assert.match(battleSource, /포인트 \{ranked\.profile\.rating\}/);
  assert.doesNotMatch(battleSource, />MMR</);
  assert.doesNotMatch(battleSource, /방어대 계정 만들기/);
  assert.doesNotMatch(battleSource, /온라인 경기의 MMR, 티어와 승패 기록/);
  assert.match(battleSource, /matchId: crypto\.randomUUID\(\)/);
  assert.match(rules, /"rankedUsers"/);
  assert.match(rules, /"rankings"/);
});

test("free battle exposes room creation, joining, and four connected slots", async () => {
  const source = await readFile(new URL("../app/free-battle.tsx", import.meta.url), "utf8");
  assert.match(source, /온라인 대전/);
  assert.match(source, /1 : 1/);
  assert.match(source, /2 : 2/);
  assert.match(source, /새 방 만들기/);
  assert.match(source, /방 코드 6자리/);
  assert.match(source, /Array\.from\(\{ length: online\.matchSize \}/);
  assert.match(source, /TURN 없이 직접 연결만 사용합니다/);
  assert.match(source, /참가 가능한 게임방/);
  assert.match(source, /새로고침/);
  assert.match(source, /online\.availableRooms\.map/);
  assert.match(source, /draftSettings\.mode === "online" \|\| !openOnlineRoomCode/);
  assert.match(source, /void leaveOnlineRoom\(\)/);
  assert.match(source, /새 대전방 만들기/);
  assert.match(source, /tab-icon" aria-hidden="true">💻/);
  assert.match(source, /tab-icon" aria-hidden="true">👥/);
  assert.match(source, /tab-icon" aria-hidden="true">🌐/);
  assert.match(source, /방 제목 <em>필수<\/em>/);
  assert.match(source, /room-create-modal[\s\S]*room-create-board-size[\s\S]*room-create-match-size/);
  assert.doesNotMatch(source, /!online\.roomCode && \(\s*<div className="online-board-select"/);
  assert.match(source, /비밀번호 사용/);
  assert.match(source, /방 비밀번호 입력/);
  assert.match(source, /room\.hasPassword/);
});
